# Generated by Django 3.1.2 on 2020-11-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('Xcoor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Ycoor', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
